const heading=document.getElementById('main-heading');
const header=document.getElementById('header');
const basketHeading=document.getElementById('basket-heading');
heading.textContent='Fruit World';
const thanks=document.getElementById('thanks');
heading.style.color='orange';
header.style.backgroundColor='green'
header.style.borderBottom='orange';
basketHeading.style.color='darkgreen';
thanks.innerHTML='<p>Please visit us again</p>'